export const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST';
export const ADD_TASK_SUCCEED = 'ADD_TASK_SUCCEED';
export const ADD_TASK_FAILED = 'ADD_TASK_FAILED';

export const GET_TASKS_SUCCEED = 'GET_TASKS_SUCCEED';
export const GET_TASKS_FAILED = 'GET_TASKS_FAILED';

export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST';
export const DELETE_TASK_SUCCEED = 'DELETE_TASK_SUCCEED';
export const DELETE_TASK_FAILED = 'DELETE_TASK_FAILED';

export const UPDATE_TASK_REQUEST = 'UPDATE_TASK_REQUEST';
export const UPDATE_TASK_SUCCEED = 'UPDATE_TASK_SUCCEED';
export const UPDATE_TASK_FAILED = 'UPDATE_TASK_FAILED';

